
/process/optical/processActivation Scintillation false

/run/initialize

#/gps/particle ion
#/gps/ion 2 3

/gps/particle proton

/gps/pos/type Surface
/gps/pos/shape Sphere
/gps/pos/centre 0 0 0 cm
/gps/pos/radius 70 mm

/gps/ang/type cos
/gps/ene/type Mono

/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 90 deg

/gps/energy 70 MeV
/analysis/setFileName /home/heplab/marina/lisa/RadMon/results/data/sphere_mono/p_70MeV.root
/run/beamOn 10000000

/gps/energy 100 MeV
/analysis/setFileName /home/heplab/marina/lisa/RadMon/results/data/sphere_mono/p_100MeV.root
/run/beamOn 10000000

/gps/energy 158 MeV
/analysis/setFileName /home/heplab/marina/lisa/RadMon/results/data/sphere_mono/p_158MeV.root
/run/beamOn 10000000

/gps/energy 251 MeV
/analysis/setFileName /home/heplab/marina/lisa/RadMon/results/data/sphere_mono/p_251MeV.root
/run/beamOn 10000000

/gps/energy 398 MeV
/analysis/setFileName /home/heplab/marina/lisa/RadMon/results/data/sphere_mono/p_398MeV.root
/run/beamOn 10000000

/gps/energy 630 MeV
/analysis/setFileName /home/heplab/marina/lisa/RadMon/results/data/sphere_mono/p_630MeV.root
/run/beamOn 10000000

/gps/energy 1000 MeV
/analysis/setFileName /home/heplab/marina/lisa/RadMon/results/data/sphere_mono/p_1000MeV.root
/run/beamOn 10000000
