/run/initialize

#/gps/particle ion
#/gps/ion 2 3

/gps/particle proton

/gps/pos/type Surface
/gps/pos/shape Sphere
/gps/pos/centre 0 0 0 cm
/gps/pos/radius 70 mm

/gps/ang/type cos
/gps/ene/type Mono

/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 90 deg

/gps/energy 100 MeV
/analysis/setFileName /home/heplab/marina/lisa/RadMon/results/abs10-25-35mm/sphereR7_mono/p_100MeV.csv
/run/beamOn 1000000

/gps/energy 200 MeV
/analysis/setFileName /home/heplab/marina/lisa/RadMon/results/abs10-25-35mm/sphereR7_mono/p_200MeV.csv
/run/beamOn 1000000

/gps/energy 300 MeV
/analysis/setFileName /home/heplab/marina/lisa/RadMon/results/abs10-25-35mm/sphereR7_mono/p_300MeV.csv
/run/beamOn 1000000

/gps/energy 500 MeV
/analysis/setFileName /home/heplab/marina/lisa/RadMon/results/abs10-25-35mm/sphereR7_mono/p_500MeV.csv
/run/beamOn 1000000

/gps/energy 700 MeV
/analysis/setFileName /home/heplab/marina/lisa/RadMon/results/abs10-25-35mm/sphereR7_mono/p_700MeV.csv
/run/beamOn 1000000

/gps/energy 1 GeV
/analysis/setFileName /home/heplab/marina/lisa/RadMon/results/abs10-25-35mm/sphereR7_mono/p_1GeV.csv
/run/beamOn 1000000

/gps/energy 2 GeV
/analysis/setFileName /home/heplab/marina/lisa/RadMon/results/abs10-25-35mm/sphereR7_mono/p_2GeV.csv
/run/beamOn 1000000
